IF(NOT SCOREP_ROOT)
  SET(SCOREP_ROOT $ENV{SCOREP_ROOT})
ENDIF()

FIND_PATH(SCOREP_INCLUDE_DIR NAMES scorep/SCOREP_User.h PATHS ${SCOREP_ROOT}/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SCOREP DEFAULT_MSG SCOREP_INCLUDE_DIR)

IF   (NOT SCOREP_FOUND)
  MESSAGE(FATAL_ERROR "ScoreP not found.")
ENDIF(NOT SCOREP_FOUND)

MARK_AS_ADVANCED(SCOREP_INCLUDE_DIR)